/**
 * İtemSepeti — Initial Catalog Seed Dataset
 * Games, Categories, Game Servers and Sample Products for Dev/Staging/Testing.
 */

import {
  ItemSepetiGame,
  ItemSepetiCategory,
  ItemSepetiProduct,
} from "@/types/marketplace";

export const SEED_GAMES: ItemSepetiGame[] = [
  {
    id: "game_cs2",
    slug: "cs2",
    name: "CS2 (Counter-Strike 2)",
    publisher: "Valve",
    isActive: true,
    supportedProductTypes: ["ITEM", "ACCOUNT"],
    createdAt: 1725700000000,
    updatedAt: 1725700000000,
  },
  {
    id: "game_metin2",
    slug: "metin2",
    name: "Metin2",
    publisher: "Gameforge",
    isActive: true,
    supportedProductTypes: ["CURRENCY", "ITEM", "ACCOUNT"],
    servers: [
      { id: "srv_marmara", name: "Marmara", isActive: true },
      { id: "srv_turkiye", name: "Türkiye", isActive: true },
      { id: "srv_anadolu", name: "Anadolu", isActive: true },
    ],
    createdAt: 1725700000000,
    updatedAt: 1725700000000,
  },
  {
    id: "game_valorant",
    slug: "valorant",
    name: "Valorant",
    publisher: "Riot Games",
    isActive: true,
    supportedProductTypes: ["DIGITAL_CODE", "ACCOUNT"],
    createdAt: 1725700000000,
    updatedAt: 1725700000000,
  },
  {
    id: "game_pubg",
    slug: "pubg",
    name: "PUBG Mobile",
    publisher: "Tencent",
    isActive: true,
    supportedProductTypes: ["CURRENCY", "ACCOUNT"],
    createdAt: 1725700000000,
    updatedAt: 1725700000000,
  },
  {
    id: "game_steam",
    slug: "steam",
    name: "Steam",
    publisher: "Valve",
    isActive: true,
    supportedProductTypes: ["DIGITAL_CODE"],
    createdAt: 1725700000000,
    updatedAt: 1725700000000,
  },
];

export const SEED_CATEGORIES: ItemSepetiCategory[] = [
  {
    id: "cat_cs2_skins",
    gameId: "game_cs2",
    slug: "skins",
    name: "Silah Skinleri & Bıçaklar",
    productType: "ITEM",
    defaultDeliveryMethod: "MANUAL_ITEM",
    platformFeeRate: 0.05, // %5
    minPrice: 10,
    maxPrice: 250000,
    isActive: true,
    createdAt: 1725700000000,
  },
  {
    id: "cat_cs2_cases",
    gameId: "game_cs2",
    slug: "kasalar",
    name: "Kasalar & Kapsüller",
    productType: "ITEM",
    defaultDeliveryMethod: "MANUAL_ITEM",
    platformFeeRate: 0.05,
    minPrice: 5,
    maxPrice: 50000,
    isActive: true,
    createdAt: 1725700000000,
  },
  {
    id: "cat_metin2_yang",
    gameId: "game_metin2",
    slug: "yang",
    name: "Yang & Won",
    productType: "CURRENCY",
    defaultDeliveryMethod: "CURRENCY_TRADE",
    platformFeeRate: 0.06, // %6
    minPrice: 20,
    maxPrice: 100000,
    isActive: true,
    createdAt: 1725700000000,
  },
  {
    id: "cat_metin2_items",
    gameId: "game_metin2",
    slug: "itemler",
    name: "Efsunlu İtemler & Zırhlar",
    productType: "ITEM",
    defaultDeliveryMethod: "MANUAL_ITEM",
    platformFeeRate: 0.06,
    minPrice: 50,
    maxPrice: 200000,
    isActive: true,
    createdAt: 1725700000000,
  },
  {
    id: "cat_valorant_vp",
    gameId: "game_valorant",
    slug: "vp",
    name: "Valorant Points (VP) E-Pin",
    productType: "DIGITAL_CODE",
    defaultDeliveryMethod: "AUTOMATIC_CODE",
    platformFeeRate: 0.03, // %3
    minPrice: 50,
    maxPrice: 10000,
    isActive: true,
    createdAt: 1725700000000,
  },
  {
    id: "cat_pubg_uc",
    gameId: "game_pubg",
    slug: "uc",
    name: "Unknown Cash (UC)",
    productType: "CURRENCY",
    defaultDeliveryMethod: "DIRECT_TRANSFER",
    platformFeeRate: 0.04, // %4
    minPrice: 30,
    maxPrice: 15000,
    isActive: true,
    createdAt: 1725700000000,
  },
  {
    id: "cat_steam_wallet",
    gameId: "game_steam",
    slug: "cuzdan-kodu",
    name: "Steam Cüzdan Kodları",
    productType: "DIGITAL_CODE",
    defaultDeliveryMethod: "AUTOMATIC_CODE",
    platformFeeRate: 0.03,
    minPrice: 20,
    maxPrice: 5000,
    isActive: true,
    createdAt: 1725700000000,
  },
];

export const SEED_PRODUCTS: ItemSepetiProduct[] = [
  {
    id: "prod_cs2_ak47_asiimov",
    gameId: "game_cs2",
    gameName: "CS2 (Counter-Strike 2)",
    productType: "ITEM",
    categoryId: "cat_cs2_skins",
    categoryName: "Silah Skinleri & Bıçaklar",
    name: "AK-47 | Asiimov",
    slug: "ak47-asiimov",
    normalizedName: "ak47 asiimov",
    description: "Popüler fütüristik bilim kurgu temalı CS2 tüfek skini.",
    isActive: true,
    createdAt: 1725700000000,
    updatedAt: 1725700000000,
  },
  {
    id: "prod_cs2_karambit_doppler",
    gameId: "game_cs2",
    gameName: "CS2 (Counter-Strike 2)",
    productType: "ITEM",
    categoryId: "cat_cs2_skins",
    categoryName: "Silah Skinleri & Bıçaklar",
    name: "★ Karambit | Doppler",
    slug: "karambit-doppler",
    normalizedName: "karambit doppler",
    description: "Kavisli kaplan pençesi bıçak, Doppler fazlı özel desen.",
    isActive: true,
    createdAt: 1725700000000,
    updatedAt: 1725700000000,
  },
  {
    id: "prod_metin2_yang_100m",
    gameId: "game_metin2",
    gameName: "Metin2",
    productType: "CURRENCY",
    categoryId: "cat_metin2_yang",
    categoryName: "Yang & Won",
    name: "100M Yang Paketi",
    slug: "100m-yang-paketi",
    normalizedName: "100m yang paketi",
    description: "Sunucu içi teslimatla anında aktarılabilir 100 milyon Yang.",
    isActive: true,
    createdAt: 1725700000000,
    updatedAt: 1725700000000,
  },
  {
    id: "prod_valorant_vp_1200",
    gameId: "game_valorant",
    gameName: "Valorant",
    productType: "DIGITAL_CODE",
    categoryId: "cat_valorant_vp",
    categoryName: "Valorant Points (VP) E-Pin",
    name: "Valorant 1200 VP",
    slug: "valorant-1200-vp",
    normalizedName: "valorant 1200 vp",
    description: "Riot Games TR bölgesi uyumlu anında teslim 1200 VP kodu.",
    isActive: true,
    createdAt: 1725700000000,
    updatedAt: 1725700000000,
  },
];
