import { Restaurant, Category, MenuItem, Table, Ingredient, WasteLog, HappyHourRule } from "@/types/restaurant";

export const DEMO_INGREDIENTS: Ingredient[] = [
  { id: "ing_beef_burger", name: "Kuru Dinlendirilmiş Dana Kıyma", unit: "kg", unitCost: 480, currentStock: 24.5, criticalStock: 5.0, category: "ET", lastRestockedAt: "2026-08-19" },
  { id: "ing_brioche_bun", name: "Tereyağlı Brioche Burger Ekmeği", unit: "adet", unitCost: 8.5, currentStock: 140, criticalStock: 30, category: "UNLU_MAMUL", lastRestockedAt: "2026-08-19" },
  { id: "ing_cheddar", name: "12 Aylık Olgunlaştırılmış Cheddar", unit: "kg", unitCost: 340, currentStock: 12.0, criticalStock: 3.0, category: "SUT_URUNU", lastRestockedAt: "2026-08-18" },
  { id: "ing_truffle_mayo", name: "Taze Trüf & Aioli Mayonezi", unit: "kg", unitCost: 290, currentStock: 8.5, criticalStock: 2.0, category: "SOS", lastRestockedAt: "2026-08-19" },
  { id: "ing_dry_aged_beef", name: "28 Gün Dry-Aged Dana Antrikot", unit: "kg", unitCost: 850, currentStock: 18.0, criticalStock: 4.0, category: "ET", lastRestockedAt: "2026-08-17" },
  { id: "ing_lamb_chops", name: "Taze Süt Kuzu Pirzola", unit: "kg", unitCost: 720, currentStock: 15.0, criticalStock: 3.0, category: "ET", lastRestockedAt: "2026-08-18" },
  { id: "ing_burrata", name: "Taze Puglia Manda Burrata (125g)", unit: "adet", unitCost: 65, currentStock: 35, criticalStock: 8, category: "SUT_URUNU", lastRestockedAt: "2026-08-19" },
  { id: "ing_pizza_dough", name: "48 Saat Mayalanmış Napoliten Hamur", unit: "adet", unitCost: 12, currentStock: 80, criticalStock: 20, category: "UNLU_MAMUL", lastRestockedAt: "2026-08-19" },
  { id: "ing_san_marzano", name: "DOP San Marzano Domates Sosu", unit: "l", unitCost: 95, currentStock: 25, criticalStock: 5, category: "SOS", lastRestockedAt: "2026-08-16" },
  { id: "ing_callebaut", name: "Callebaut %70 Belçika Çikolatası", unit: "kg", unitCost: 420, currentStock: 10, criticalStock: 2.5, category: "DIGER", lastRestockedAt: "2026-08-15" },
  { id: "ing_coffee_beans", name: "%100 Arabica Ethiopia Yirgacheffe", unit: "kg", unitCost: 480, currentStock: 14, criticalStock: 3.0, category: "ICECEK", lastRestockedAt: "2026-08-18" },
];

export const DEMO_WASTE_LOGS: WasteLog[] = [
  {
    id: "waste_1",
    ingredientId: "ing_brioche_bun",
    ingredientName: "Tereyağlı Brioche Burger Ekmeği",
    quantity: 6,
    unit: "adet",
    cost: 51,
    reason: "DAMAGED",
    loggedAt: "2026-08-19T22:30:00.000Z",
    loggedBy: "Şef Mehmet",
  },
  {
    id: "waste_2",
    ingredientId: "ing_burrata",
    ingredientName: "Taze Puglia Manda Burrata (125g)",
    quantity: 1,
    unit: "adet",
    cost: 65,
    reason: "PREPARATION_ERROR",
    loggedAt: "2026-08-19T20:15:00.000Z",
    loggedBy: "Mutfak Ekibi",
  },
];

export const DEMO_HAPPY_HOUR_RULES: HappyHourRule[] = [
  {
    id: "hh_1",
    title: "Öğleden Sonra Kahve Molası",
    discountPercent: 15,
    startHour: 14,
    endHour: 17,
    targetCategoryId: "cat_coffee",
    isActive: true,
  },
  {
    id: "hh_2",
    title: "Akşamüstü Burger Keyfi",
    discountPercent: 10,
    startHour: 16,
    endHour: 18,
    targetCategoryId: "cat_burgers",
    isActive: false,
  },
];

export const DEMO_RESTAURANT: Restaurant = {
  id: "rest_aura_bistro",
  slug: "aura-bistro",
  name: "Aura Bistro & Lounge",
  description: "Modern Akdeniz mutfağı, 28 gün kuru dinlendirilmiş etler, el yapımı gurme burgerler, odun ateşinde pizza ve imza kokteyller.",
  logo: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&auto=format&fit=crop&q=80",
  settings: {
    orderMode: "WAITER_CONFIRMATION", // Garson/Kasa Onaylı Mod
    paymentMode: "HYBRID", // Hem masada hem kasada ödeme
    wifiRequired: false, // 4.5G/5G hücresel uyumlu
    sessionTimeoutMinutes: 15,
    currency: "TL",
    taxRatePercent: 10,
    serviceChargePercent: 0,
    allowSplitBill: true,
    googleReviewUrl: "https://maps.google.com",
    posIntegrationType: "STANDALONE",
    themeColor: "#00A6A6",
    address: "Bağdat Caddesi No: 214, Kadıköy / İstanbul",
    phone: "+90 216 444 0 214",
  },
  createdAt: "2026-01-01T00:00:00.000Z",
  updatedAt: "2026-01-01T00:00:00.000Z",
};

export const DEMO_CATEGORIES: Category[] = [
  { id: "cat_popular", restaurantId: "rest_aura_bistro", name: "Şefin İmzaları & Popüler", icon: "Flame", order: 1, isActive: true },
  { id: "cat_starters", restaurantId: "rest_aura_bistro", name: "Başlangıçlar & Paylaşımlık", icon: "Salad", order: 2, isActive: true },
  { id: "cat_burgers", restaurantId: "rest_aura_bistro", name: "Gurme Burgerler", icon: "Sandwich", order: 3, isActive: true },
  { id: "cat_pizzas", restaurantId: "rest_aura_bistro", name: "Taş Fırın Napoliten Pizza", icon: "Pizza", order: 4, isActive: true },
  { id: "cat_mains", restaurantId: "rest_aura_bistro", name: "Kuru Dinlendirilmiş Etler & Izgara", icon: "Beef", order: 5, isActive: true },
  { id: "cat_seafood", restaurantId: "rest_aura_bistro", name: "Deniz Ürünleri & Taze Balık", icon: "Fish", order: 6, isActive: true },
  { id: "cat_pastas", restaurantId: "rest_aura_bistro", name: "El Yapımı Taze Makarnalar", icon: "Soup", order: 7, isActive: true },
  { id: "cat_drinks", restaurantId: "rest_aura_bistro", name: "İmza Kokteyller & İçecekler", icon: "Wine", order: 8, isActive: true },
  { id: "cat_coffee", restaurantId: "rest_aura_bistro", name: "Artisan Kahveler & Çay", icon: "Coffee", order: 9, isActive: true },
  { id: "cat_desserts", restaurantId: "rest_aura_bistro", name: "Özel Tasarım Tatlılar", icon: "Cake", order: 10, isActive: true },
];

export const DEMO_MENU_ITEMS: MenuItem[] = [
  // 1. GURME BURGERLER
  {
    id: "item_truffle_burger",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_burgers",
    name: "Trüflü Gurme Dana Burger (180g)",
    description: "Kuru dinlendirilmiş dana antrikot köftesi, taze trüf mayonezi, karamelize arpacık soğan, 12 aylık eritilmiş cheddar, tereyağlı brioche ekmeği ve trüflü patates cipsi ile.",
    price: 360,
    costPrice: 114.5,
    recipe: [
      { ingredientId: "ing_beef_burger", quantity: 0.18 }, // 180g (86.4 TL)
      { ingredientId: "ing_brioche_bun", quantity: 1 }, // 1 adet (8.5 TL)
      { ingredientId: "ing_cheddar", quantity: 0.025 }, // 25g (8.5 TL)
      { ingredientId: "ing_truffle_mayo", quantity: 0.025 }, // 25g (7.25 TL)
    ],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "180g Dana Antrikot Köftesi",
      "Eritilmiş Cheddar Peyniri",
      "Karamelize Arpacık Soğan",
      "Taze Trüf Mayonezi",
      "Kornişon Turşu",
      "Çıtır Marul Yaprakları",
      "Tereyağlı Brioche Ekmek",
    ],
    preparationTimeMinutes: 15,
    calories: 820,
    allergens: ["Gluten", "Laktoz", "Yumurta"],
    badges: ["BESTSELLER", "CHEF_SPECIAL"],
    order: 1,
    optionGroups: [
      {
        id: "opt_burger_doneness",
        title: "Köfte Pişme Derecesi",
        type: "SINGLE",
        required: true,
        options: [
          { id: "doneness_med", name: "Orta (Medium - Sulu & Yumuşak)", priceDelta: 0, isDefault: true },
          { id: "doneness_well", name: "İyi Pişmiş (Well Done)", priceDelta: 0 },
          { id: "doneness_med_well", name: "Orta-İyi (Medium Well)", priceDelta: 0 },
        ],
      },
      {
        id: "opt_burger_sides",
        title: "Yan Lezzet Tercihi",
        type: "SINGLE",
        required: true,
        options: [
          { id: "side_truffle_fries", name: "Trüflü & Parmesanlı Patates Kızartması", priceDelta: 0, isDefault: true },
          { id: "side_sweet_potato", name: "Çıtır Tatlı Patates (+40 TL)", priceDelta: 40 },
          { id: "side_onion_rings", name: "El Yapımı Çıtır Soğan Halkası (+30 TL)", priceDelta: 30 },
        ],
      },
      {
        id: "opt_burger_extras",
        title: "Ekstra İlave Malzemeler",
        type: "MULTIPLE",
        options: [
          { id: "extra_bacon", name: "Çıtır Dana Füme Antrikot", priceDelta: 65 },
          { id: "extra_cheddar", name: "Çift Kat Eritilmiş Cheddar Peyniri", priceDelta: 40 },
          { id: "extra_truffle_sauce", name: "Ekstra Trüf Mantarı Sosu", priceDelta: 45 },
        ],
      },
    ],
  },
  {
    id: "item_smash_bacon_burger",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_burgers",
    name: "Çift Katlı Smash Bacon Burger",
    description: "2x 100g döküm ızgarada ezilmiş çıtır dana köftesi, duble cheddar peyniri, meşe odununda tütsülenmiş dana bacon, ev yapımı barbekü sos ve turşu.",
    price: 385,
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "2x 100g Dana Smash Köfte",
      "Tütsülenmiş Dana Bacon",
      "Çift Kat Cheddar Peyniri",
      "Ev Yapımı BBQ Sos",
      "Kornişon Turşu Dilimleri",
      "Kırmızı Halka Soğan",
    ],
    preparationTimeMinutes: 12,
    calories: 940,
    allergens: ["Gluten", "Laktoz", "Hardal"],
    badges: ["BESTSELLER"],
    order: 2,
    optionGroups: [
      {
        id: "opt_smash_bun",
        title: "Ekmek Tercihi",
        type: "SINGLE",
        required: true,
        options: [
          { id: "bun_brioche", name: "Tereyağlı Yumuşak Brioche", priceDelta: 0, isDefault: true },
          { id: "bun_pretzel", name: "Tuzlu Pretzel Ekmeği", priceDelta: 25 },
        ],
      },
    ],
  },

  // 2. KURU DİNLENDİRİLMİŞ ET & IZGARA
  {
    id: "item_ribeye_steak",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_mains",
    name: "28 Gün Dry-Aged Dana Antrikot (280g)",
    description: "Özel tuz odasında 28 gün dinlendirilmiş dana antrikot, kadife patates püresi, kömür ateşinde ızgara kuşkonmaz, fırınlanmış sarımsak ve biberiye tereyağı sosu ile.",
    price: 720,
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "280g Kuru Dinlendirilmiş Dana Antrikot",
      "Taze Dağ Biberiyesi",
      "Izgara Yeşil Kuşkonmaz",
      "Tereyağlı Patates Püresi",
      "Köz Sarımsak",
    ],
    preparationTimeMinutes: 20,
    calories: 780,
    allergens: ["Laktoz"],
    badges: ["CHEF_SPECIAL"],
    order: 3,
    optionGroups: [
      {
        id: "opt_steak_doneness",
        title: "Et Pişme Derecesi",
        type: "SINGLE",
        required: true,
        options: [
          { id: "steak_rare", name: "Az Pişmiş (Rare)", priceDelta: 0 },
          { id: "steak_med_rare", name: "Az-Orta (Medium Rare - Şefin Tavsiyesi)", priceDelta: 0, isDefault: true },
          { id: "steak_med", name: "Orta (Medium)", priceDelta: 0 },
          { id: "steak_well", name: "İyi Pişmiş (Well Done)", priceDelta: 0 },
        ],
      },
      {
        id: "opt_steak_sauce",
        title: "Sos Seçimi",
        type: "SINGLE",
        required: true,
        options: [
          { id: "sauce_peppercorn", name: "Yeşil Tane Karabiber Sosu", priceDelta: 0, isDefault: true },
          { id: "sauce_chimichurri", name: "Taze Otlu Arjantin Chimichurri Sos", priceDelta: 0 },
          { id: "sauce_gorgonzola", name: "Mavi Peynir & Gravy Sos (+45 TL)", priceDelta: 45 },
        ],
      },
    ],
  },
  {
    id: "item_lamb_chops",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_mains",
    name: "Taze Dağ Kekikli Kuzu Pirzola",
    description: "Kömür ızgarasında marine edilmiş 3 parça kuzu pirzola, fırınlanmış bebek patates, közlenmiş kapya biber ve taze nane pestosu.",
    price: 640,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "3 Kalem Marine Kuzu Pirzola",
      "Fırın Bebek Patates",
      "Köz Kapya Biber",
      "Taze Nane Pestosu",
      "Dağ Kekiği",
    ],
    preparationTimeMinutes: 18,
    calories: 710,
    badges: ["CHEF_SPECIAL"],
    order: 4,
  },

  // 3. TAŞ FIRIN NAPOLİTEN PİZZA
  {
    id: "item_burrata_pizza",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_pizzas",
    name: "Taze Burrata & Fesleğen Pesto Pizza",
    description: "48 saat mayalanmış Napoliten hamuru, San Marzano domates sosu, manda mozzarella, fırın çıkışı yerleştirilen 125g taze Puglia burrata peyniri ve çam fıstığı.",
    price: 440,
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "San Marzano Domates Sosu",
      "Manda Mozzarella",
      "125g Taze Puglia Burrata",
      "Taze Fesleğen Yaprakları",
      "Kavrulan Çam Fıstığı",
      "Sızma Zeytinyağı",
    ],
    preparationTimeMinutes: 12,
    calories: 910,
    allergens: ["Gluten", "Laktoz", "Kuruyemiş"],
    badges: ["BESTSELLER", "CHEF_SPECIAL"],
    order: 5,
    optionGroups: [
      {
        id: "opt_pizza_crust",
        title: "Kenar Hamur Tercihi",
        type: "SINGLE",
        required: true,
        options: [
          { id: "crust_classic", name: "Klasik İtalyan İnce Hamur", priceDelta: 0, isDefault: true },
          { id: "crust_mozzarella", name: "Manda Mozzarella Dolgulu Kenar (+55 TL)", priceDelta: 55 },
        ],
      },
    ],
  },
  {
    id: "item_quattro_formaggi",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_pizzas",
    name: "Quattro Formaggi (4 Peynirli & Ballı)",
    description: "Fior di latte mozzarella, gorgonzola mavi peynir, parmesan, fontina ve servis anında gezdirilen kestane balı damlaları.",
    price: 410,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "Fior di Latte Mozzarella",
      "Gorgonzola Peyniri",
      "Grana Padano Parmesan",
      "Fontina Peyniri",
      "Kestane Balı Damlaları",
    ],
    preparationTimeMinutes: 12,
    calories: 890,
    allergens: ["Gluten", "Laktoz"],
    order: 6,
  },

  // 4. BAŞLANGIÇLAR & PAYLAŞIMLIK
  {
    id: "item_burrata_bruschetta",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_starters",
    name: "Közlenmiş Çeri Domatesli Burrata Bruschetta",
    description: "Ekşi mayalı çıtır odun ekmeği üzerine sarımsaklı zeytinyağı, fırınlanmış salkım domates, taze burrata parçaları ve balzamik sirke havyarı.",
    price: 240,
    image: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "Ekşi Mayalı Çıtır Ekmek",
      "Fırınlanmış Çeri Domates",
      "Taze Burrata Peyniri",
      "Sarımsaklı Zeytinyağı",
      "Balzamik Havyarı",
    ],
    preparationTimeMinutes: 8,
    calories: 340,
    allergens: ["Gluten", "Laktoz"],
    badges: ["BESTSELLER"],
    order: 7,
  },
  {
    id: "item_crispy_calamari",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_starters",
    name: "Ege Usulü Çıtır Bebek Kalamar Tava",
    description: "Hafif pane kaplamalı taze bebek kalamar halkaları, limon kabuklu ev yapımı tarator sos ve taze roka yaprakları ile.",
    price: 360,
    image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "Taze Bebek Kalamar Halkaları",
      "Cevizli Ev Tarator Sosu",
      "Taze Roka Yaprakları",
      "Izgara Limon",
    ],
    preparationTimeMinutes: 10,
    calories: 460,
    allergens: ["Deniz Ürünleri", "Gluten", "Yumurta"],
    order: 8,
  },
  {
    id: "item_truffle_fries_bowl",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_starters",
    name: "Trüf & 24 Aylık Parmesanlı Çıtır Patates",
    description: "İnce kesim çıtır patates, beyaz trüf yağı, rendelenmiş 24 aylık Grana Padano parmesan ve taze frenk soğanı.",
    price: 190,
    image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "İnce Kesim Çıtır Patates",
      "Beyaz Trüf Yağı",
      "24 Aylık Grana Padano Parmesan",
      "İnce Kıyılmış Frenk Soğanı",
    ],
    preparationTimeMinutes: 6,
    calories: 410,
    allergens: ["Laktoz"],
    order: 9,
  },

  // 5. DENİZ ÜRÜNLERİ & MAKARNA
  {
    id: "item_grilled_salmon",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_seafood",
    name: "Fırınlanmış Norveç Somon Fileto",
    description: "Kök sebzeler ve teriyaki sos ile marine edilmiş Norveç somonu, kereviz püresi, çıtır kapari ve limon tereyağı sosu.",
    price: 560,
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "Norveç Somon Fileto (200g)",
      "İpeksi Kereviz Püresi",
      "Çıtır Kapari Taneleri",
      "Limon & Dereotu Tereyağı",
    ],
    preparationTimeMinutes: 16,
    calories: 590,
    allergens: ["Balık", "Laktoz"],
    badges: ["CHEF_SPECIAL"],
    order: 10,
  },
  {
    id: "item_seafood_linguine",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_pastas",
    name: "Karides & Kum Midyeli Deniz Mahsullü Linguine",
    description: "Taze el yapımı linguine makarnası, jumbo karides, kum midyesi, kalamar, sarımsak, taze fesleğen ve hafif bisque sos.",
    price: 480,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "El Yapımı Taze Linguine",
      "Jumbo Deniz Karidesi",
      "Kum Midyesi",
      "Bebek Kalamar",
      "Taze Fesleğenli Bisque Sos",
      "Sarımsak",
    ],
    preparationTimeMinutes: 15,
    calories: 640,
    allergens: ["Gluten", "Deniz Ürünleri", "Kabuklular"],
    order: 11,
  },
  {
    id: "item_parmesan_fettuccine",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_pastas",
    name: "Porçini Mantarlı & Trüflü Taze Fettuccine",
    description: "Günlük taze açılmış yumurtalı fettuccine, dağ porçini mantarları kreması, 24 aylık parmesan ve taze kekik yaprakları.",
    price: 380,
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281035?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "Taze Yumurtalı Fettuccine",
      "Dağ Porçini Mantarı",
      "Trüf Kreması",
      "24 Aylık Grana Padano Parmesan",
      "Taze Kekik",
    ],
    preparationTimeMinutes: 14,
    calories: 680,
    allergens: ["Gluten", "Laktoz", "Yumurta"],
    badges: ["BESTSELLER"],
    order: 12,
  },

  // 6. İMZA KOKTEYLLER & İÇECEKLER
  {
    id: "item_smoked_berry_cocktail",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_drinks",
    name: "Tütsülenmiş Berry & Hibiscus İmza Kokteyl",
    description: "Ev yapımı hibiskus şurubu, orman meyveleri özütü, taze misket limonu suyu, biberiye tütsüsü ve zencefil gazozu.",
    price: 260,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "Orman Meyveleri Özütü",
      "Hibiskus Şurubu",
      "Taze Lime (Misket Limonu)",
      "Biberiye Tütsüsü",
      "Zencefil Gazozu",
    ],
    preparationTimeMinutes: 4,
    calories: 160,
    badges: ["CHEF_SPECIAL"],
    order: 13,
  },
  {
    id: "item_passion_mocktail",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_drinks",
    name: "Passion Fruit & Taze Nane Mocktail (Alkolsüz)",
    description: "Egzotik çarkıfelek meyvesi püresi, taze ezilmiş nane yaprakları, adaçayı infüzyonu ve soda.",
    price: 180,
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "Çarkıfelek Meyvesi Püresi",
      "Taze Nane Yaprakları",
      "Adaçayı İnfüzyonu",
      "Doğal Maden Suyu",
      "Buz",
    ],
    preparationTimeMinutes: 3,
    calories: 120,
    badges: ["VEGAN"],
    order: 14,
  },
  {
    id: "item_artisan_latte",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_coffee",
    name: "Single Origin Yirgacheffe Flat White & Latte",
    description: "Etiyopya Yirgacheffe %100 Arabica çekirdeklerinden çift shot espresso ve kadife dokulu mikro köpürtülmüş süt.",
    price: 120,
    image: "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "Çift Shot Etiyopya Espresso",
      "Mikro Köpürtülmüş Barista Sütü",
    ],
    preparationTimeMinutes: 4,
    calories: 110,
    allergens: ["Laktoz (Yulaf/Badem Sütü Seçilebilir)"],
    order: 15,
  },

  // 7. ÖZEL TASARIM TATLILAR
  {
    id: "item_san_sebastian",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_desserts",
    name: "Belçika Çikolatalı San Sebastian Cheesecake",
    description: "Akışkan fırınlanmış İspanyol cheesecake'i, masada sıcak dökülen eritilmiş Callebaut Belçika sütlü çikolatası ve taze çilek eşliğinde.",
    price: 240,
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "Akışkan San Sebastian Dilimi",
      "Sıcak Callebaut Belçika Çikolatası",
      "Taze Dağ Çileği",
    ],
    preparationTimeMinutes: 5,
    calories: 510,
    allergens: ["Laktoz", "Yumurta"],
    badges: ["BESTSELLER"],
    order: 16,
  },
  {
    id: "item_chocolate_fondant",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_desserts",
    name: "Sıcak Valrhona Çikolatalı Sufle & Vanilyalı Dondurma",
    description: "%70 Valrhona bitter çikolatadan fırından yeni çıkmış akışkan sufle, Madagaskar vanilyalı artisan dondurma ve antep fıstığı tozu ile.",
    price: 260,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=85",
    isAvailable: true,
    ingredients: [
      "%70 Valrhona Bitter Çikolata",
      "Madagaskar Vanilyalı Dondurma",
      "Gaziantep Toz Fıstık",
    ],
    preparationTimeMinutes: 12,
    calories: 580,
    allergens: ["Gluten", "Laktoz", "Yumurta", "Fıstık"],
    badges: ["CHEF_SPECIAL"],
    order: 17,
  },
];

export const DEMO_TABLES: Table[] = [
  { id: "m-1", restaurantId: "rest_aura_bistro", tableNumber: "Masa 1", section: "İç Mekan", capacity: 2, status: "EMPTY", activeBillTotal: 0 },
  { id: "m-2", restaurantId: "rest_aura_bistro", tableNumber: "Masa 2", section: "İç Mekan", capacity: 4, status: "OCCUPIED", activeBillTotal: 745, lastOrderTime: "12 dk önce" },
  { id: "m-3", restaurantId: "rest_aura_bistro", tableNumber: "Masa 3", section: "İç Mekan", capacity: 4, status: "EMPTY", activeBillTotal: 0 },
  { id: "m-4", restaurantId: "rest_aura_bistro", tableNumber: "Masa 4", section: "Teras VIP", capacity: 6, status: "WAITER_CALLED", activeBillTotal: 1540, lastCallType: "WAITER", lastCallTime: "2 dk önce" },
  { id: "m-5", restaurantId: "rest_aura_bistro", tableNumber: "Masa 5", section: "Teras", capacity: 2, status: "BILL_REQUESTED", activeBillTotal: 680, lastCallType: "BILL_CARD", lastCallTime: "1 dk önce" },
  { id: "m-6", restaurantId: "rest_aura_bistro", tableNumber: "Masa 6", section: "Bahçe", capacity: 4, status: "EMPTY", activeBillTotal: 0 },
  { id: "m-7", restaurantId: "rest_aura_bistro", tableNumber: "Masa 7", section: "Bahçe", capacity: 8, status: "OCCUPIED", activeBillTotal: 2480, lastOrderTime: "25 dk önce" },
  { id: "m-8", restaurantId: "rest_aura_bistro", tableNumber: "Masa 8", section: "VIP Lounge", capacity: 10, status: "EMPTY", activeBillTotal: 0 },
];
