import { Restaurant, Category, MenuItem, Table } from "@/types/restaurant";

export const DEMO_RESTAURANT: Restaurant = {
  id: "rest_aura_bistro",
  slug: "aura-bistro",
  name: "Aura Bistro & Lounge",
  description: "Modern Akdeniz mutfağı, el yapımı gurme burgerler, odun ateşinde pizza ve özel kokteyller.",
  logo: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=200&auto=format&fit=crop&q=80",
  settings: {
    orderMode: "WAITER_CONFIRMATION", // Garson/Kasa Onaylı Mod
    paymentMode: "HYBRID", // Hem masada hem kasada ödeme
    wifiRequired: false, // 4.5G/5G hücresel uyumlu
    sessionTimeoutMinutes: 15,
    currency: "TL",
    taxRatePercent: 10,
    serviceChargePercent: 0,
    allowSplitBill: true,
    posIntegrationType: "STANDALONE",
    themeColor: "#00A6A6",
    address: "Bağdat Caddesi No: 214, Kadıköy / İstanbul",
    phone: "+90 216 444 0 214",
  },
  createdAt: "2026-01-01T00:00:00.000Z",
  updatedAt: "2026-01-01T00:00:00.000Z",
};

export const DEMO_CATEGORIES: Category[] = [
  { id: "cat_popular", restaurantId: "rest_aura_bistro", name: "Popüler & Şefin Seçimleri", icon: "Flame", order: 1, isActive: true },
  { id: "cat_burgers", restaurantId: "rest_aura_bistro", name: "Gurme Burgerler", icon: "Utensils", order: 2, isActive: true },
  { id: "cat_pizzas", restaurantId: "rest_aura_bistro", name: "Taş Fırın Pizza", icon: "Pizza", order: 3, isActive: true },
  { id: "cat_mains", restaurantId: "rest_aura_bistro", name: "Ana Yemekler & Izgaralar", icon: "Beef", order: 4, isActive: true },
  { id: "cat_pastas", restaurantId: "rest_aura_bistro", name: "Taze Ev Yapımı Makarnalar", icon: "Soup", order: 5, isActive: true },
  { id: "cat_drinks", restaurantId: "rest_aura_bistro", name: "İçecekler & Mocktail", icon: "GlassWater", order: 6, isActive: true },
  { id: "cat_desserts", restaurantId: "rest_aura_bistro", name: "Tatlılar", icon: "Cake", order: 7, isActive: true },
];

export const DEMO_MENU_ITEMS: MenuItem[] = [
  {
    id: "item_truffle_burger",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_burgers",
    name: "Trüflü Gurme Dana Burger (180g)",
    description: "Kuru dinlendirilmiş dana köftesi, trüflü mayonez, karamelize soğan, eritilmiş cheddar ve çıtır patates.",
    price: 340,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    preparationTimeMinutes: 15,
    calories: 820,
    allergens: ["Gluten", "Laktoz", "Yumurta"],
    badges: ["BESTSELLER", "CHEF_SPECIAL"],
    order: 1,
    optionGroups: [
      {
        id: "opt_burger_doneness",
        title: "Köfte Pişme Derecesi",
        type: "SINGLE",
        required: true,
        options: [
          { id: "doneness_med", name: "Orta (Medium)", priceDelta: 0, isDefault: true },
          { id: "doneness_well", name: "İyi Pişmiş (Well Done)", priceDelta: 0 },
          { id: "doneness_med_well", name: "Orta-İyi (Medium Well)", priceDelta: 0 },
        ],
      },
      {
        id: "opt_burger_extras",
        title: "Ekstra Lezzetler",
        type: "MULTIPLE",
        options: [
          { id: "extra_bacon", name: "Çıtır Dana Füme", priceDelta: 60 },
          { id: "extra_cheddar", name: "Ekstra Çift Cheddar", priceDelta: 35 },
          { id: "extra_truffle_sauce", name: "Ekstra Trüf Sos", priceDelta: 40 },
          { id: "no_onion", name: "Soğansız İstiyorum", priceDelta: 0 },
        ],
      },
    ],
  },
  {
    id: "item_ribeye_steak",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_mains",
    name: "Közlenmiş Kuşkonmazlı Antrikot (250g)",
    description: "28 gün dinlendirilmiş dana antrikot, trüflü patates püresi, ızgara kuşkonmaz ve biberiye tereyağı sosu.",
    price: 680,
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    preparationTimeMinutes: 20,
    calories: 740,
    allergens: ["Laktoz"],
    badges: ["CHEF_SPECIAL"],
    order: 2,
    optionGroups: [
      {
        id: "opt_steak_doneness",
        title: "Et Pişme Derecesi",
        type: "SINGLE",
        required: true,
        options: [
          { id: "steak_med_rare", name: "Az-Orta (Medium Rare)", priceDelta: 0 },
          { id: "steak_med", name: "Orta (Medium)", priceDelta: 0, isDefault: true },
          { id: "steak_well", name: "İyi Pişmiş (Well Done)", priceDelta: 0 },
        ],
      },
    ],
  },
  {
    id: "item_burrata_pizza",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_pizzas",
    name: "Burrata & Pesto Taş Fırın Pizza",
    description: "San Marzano domates sosu, manda mozzarella, taze burrata peyniri, fesleğenli pesto ve çam fıstığı.",
    price: 420,
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    preparationTimeMinutes: 12,
    calories: 910,
    allergens: ["Gluten", "Laktoz", "Kuruyemiş"],
    badges: ["BESTSELLER"],
    order: 3,
    optionGroups: [
      {
        id: "opt_pizza_crust",
        title: "Kenar Seçeneği",
        type: "SINGLE",
        required: true,
        options: [
          { id: "crust_classic", name: "Klasik İtalyan İnce Hamur", priceDelta: 0, isDefault: true },
          { id: "crust_mozzarella", name: "Peynir Dolgulu Kenar", priceDelta: 50 },
        ],
      },
    ],
  },
  {
    id: "item_parmesan_fettuccine",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_pastas",
    name: "Truffle & Mantarlı Fettuccine",
    description: "Günlük taze açılmış fettuccine, porçini mantarı kreması, 24 aylık parmesan ve taze kekik.",
    price: 360,
    image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281035?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    preparationTimeMinutes: 14,
    calories: 680,
    allergens: ["Gluten", "Laktoz", "Yumurta"],
    order: 4,
  },
  {
    id: "item_passion_mocktail",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_drinks",
    name: "Passion Fruit & Nane Mocktail",
    description: "Taze çarkıfelek meyvesi püresi, taze nane yaprakları, misket limonu ve maden suyu.",
    price: 160,
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    preparationTimeMinutes: 5,
    calories: 120,
    badges: ["VEGAN"],
    order: 5,
  },
  {
    id: "item_san_sebastian",
    restaurantId: "rest_aura_bistro",
    categoryId: "cat_desserts",
    name: "Belçika Çikolatalı San Sebastian Cheesecake",
    description: "Akışkan kıvamlı fırın cheesecake, sıcak eritilmiş Callebaut Belçika sütlü çikolatası ile servis edilir.",
    price: 220,
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=600&auto=format&fit=crop&q=80",
    isAvailable: true,
    preparationTimeMinutes: 5,
    calories: 510,
    allergens: ["Laktoz", "Yumurta"],
    badges: ["BESTSELLER"],
    order: 6,
  },
];

export const DEMO_TABLES: Table[] = [
  { id: "m-1", restaurantId: "rest_aura_bistro", tableNumber: "Masa 1", section: "İç Mekan", capacity: 2, status: "EMPTY", activeBillTotal: 0 },
  { id: "m-2", restaurantId: "rest_aura_bistro", tableNumber: "Masa 2", section: "İç Mekan", capacity: 4, status: "OCCUPIED", activeBillTotal: 760, lastOrderTime: "10 dk önce" },
  { id: "m-3", restaurantId: "rest_aura_bistro", tableNumber: "Masa 3", section: "İç Mekan", capacity: 4, status: "EMPTY", activeBillTotal: 0 },
  { id: "m-4", restaurantId: "rest_aura_bistro", tableNumber: "Masa 4", section: "Teras", capacity: 6, status: "WAITER_CALLED", activeBillTotal: 1240, lastCallType: "WAITER", lastCallTime: "2 dk önce" },
  { id: "m-5", restaurantId: "rest_aura_bistro", tableNumber: "Masa 5", section: "Teras", capacity: 2, status: "BILL_REQUESTED", activeBillTotal: 580, lastCallType: "BILL_CARD", lastCallTime: "1 dk önce" },
  { id: "m-6", restaurantId: "rest_aura_bistro", tableNumber: "Masa 6", section: "Bahçe", capacity: 4, status: "EMPTY", activeBillTotal: 0 },
  { id: "m-7", restaurantId: "rest_aura_bistro", tableNumber: "Masa 7", section: "Bahçe", capacity: 8, status: "OCCUPIED", activeBillTotal: 2150, lastOrderTime: "25 dk önce" },
  { id: "m-8", restaurantId: "rest_aura_bistro", tableNumber: "Masa 8", section: "VIP Salon", capacity: 10, status: "EMPTY", activeBillTotal: 0 },
];
